'use client';
import {useEffect,useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {credit} from '@/lib/market';
type Entry={rank:number;name:string;value:number;returnPercent:number;isYou:boolean};
type Rankings={players:Entry[];yourRank:Entry|null;total:number;updatedAt:number;healthy:boolean};
export default function Leaderboard({signedIn}:{signedIn:boolean}){const [data,setData]=useState<Rankings|null>(null);const [error,setError]=useState('');
 useEffect(()=>{if(!signedIn)return;let alive=true;async function refresh(){try{const r=await fetch('/api/leaderboard',{cache:'no-store'});const d=await r.json() as Rankings & {error:string};if(!r.ok)throw new Error(d.error);if(alive){setData(d);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Leaderboard unavailable.');}}void refresh();const timer=setInterval(()=>void refresh(),60000);return()=>{alive=false;clearInterval(timer);};},[signedIn]);
 return <section className="portfolio-history"><div className="eyebrow">THE TABLE THAT COUNTS</div><h2>Player leaderboard</h2><p className="source-note">Ranked by live portfolio value. Active means a live trade in the last 30 days. Everyone starts with $1,000; demo portfolios do not count. Equal values share a rank.</p>{!signedIn?<p><a href="/login">Sign in with Google to see player rankings.</a></p>:<>{error&&<p role="alert" className="negative">{error}</p>}{!data&&!error&&<p>Loading rankings…</p>}{data&&<><p className="source-note">{data.total} active players · Market values as of {new Date(data.updatedAt).toLocaleString()}. {!data.healthy&&'Feed unavailable; values may be stale.'}</p>{!data.players.length?<p>The league is open. Make a live prediction to appear here.</p>:<Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Player</TableHead><TableHead>Portfolio</TableHead><TableHead>Return</TableHead></TableRow></TableHeader><TableBody>{data.players.map((p,i)=><TableRow key={i} className={p.isYou?'leader-you':''}><TableCell>#{p.rank}</TableCell><TableCell>{p.name}{p.isYou?' · You':''}</TableCell><TableCell>{credit(p.value)}</TableCell><TableCell className={p.returnPercent<0?'negative':'positive'}>{p.returnPercent>0?'+':''}{p.returnPercent.toFixed(2)}%</TableCell></TableRow>)}</TableBody></Table>}{data.yourRank&&data.yourRank.rank>100&&<p>Your rank: #{data.yourRank.rank} · {credit(data.yourRank.value)}</p>}<p className="source-note">Top 100 players shown. Values include available cash and marked holdings; confirmed results are reflected automatically.</p></>}</>}</section>;
}
