import {db} from './database';
export {db} from './database';
import {freshAccount,settle,type Market,type Account} from './market';
import {historyPoint,historyBucket,type HistoryPoint} from './history';
export async function loadAccount(id:string){await db().prepare('INSERT INTO portfolios (id,version,data) VALUES (?,0,?) ON CONFLICT(id) DO NOTHING').bind(id,JSON.stringify(freshAccount())).run();const row=await db().prepare('SELECT version,data FROM portfolios WHERE id=?').bind(id).first<{version:number;data:string}>();if(!row)throw new Error('Portfolio not found.');return {...JSON.parse(row.data),revision:row.version} as Account;}
export async function saveAccount(id:string,a:Account){const revision=a.revision;const next={...a,revision:revision+1};const r=await db().prepare('UPDATE portfolios SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(next),id,revision).run();if(r.meta.changes!==1)throw new Error('Your portfolio changed in another request. Refresh and try again.');return next;}
export async function settleAccount(id:string,markets:Market[]){for(let attempt=0;attempt<3;attempt++){const account=await loadAccount(id);const next=settle(account,markets);if(next.trades.length===account.trades.length)return {account,changed:false};try{return {account:await saveAccount(id,next),changed:true};}catch(e){if(!(e instanceof Error)||!e.message.includes('another request')||attempt===2)throw e;}}throw new Error('Settlement is retrying.');}
export async function settleLivePortfolios(markets:Market[],cursor=''){const rows=await db().prepare("SELECT id FROM portfolios WHERE id LIKE '%:live' AND id > ? ORDER BY id LIMIT 100").bind(cursor).all<{id:string}>();let settledAccounts=0;for(const row of rows.results){const settled=await settleAccount(row.id,markets);if(settled.changed)settledAccounts++;await recordHistory(row.id,settled.account,markets);}return {processed:rows.results.length,settledAccounts,nextCursor:rows.results.length===100?rows.results[99].id:null};}
export async function recordHistory(id:string,account:Account,markets:Market[],at=Date.now()){const p=historyPoint(account,markets,at);await db().prepare('INSERT INTO portfolio_history (portfolio_id,bucket,at,cash,value,revision) SELECT ?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM portfolios WHERE id=? AND version=?) ON CONFLICT(portfolio_id,bucket) DO UPDATE SET at=excluded.at,cash=excluded.cash,value=excluded.value,revision=excluded.revision WHERE excluded.revision>=portfolio_history.revision AND excluded.at>=portfolio_history.at').bind(id,historyBucket(at),p.at,p.cash,p.value,p.revision,id,p.revision).run();}
export async function readHistory(id:string){const result=await db().prepare('SELECT at,cash,value,revision FROM portfolio_history WHERE portfolio_id=? ORDER BY bucket DESC LIMIT 2160').bind(id).all<HistoryPoint>();return result.results.reverse();}
export async function settlementStatus(){const row=await db().prepare('SELECT data FROM feed_cache WHERE id=?').bind('sync-status').first<{data:string}>();if(!row)return {completedAt:null,healthy:false};const status=JSON.parse(row.data);return {completedAt:typeof status.completedAt==='string'?status.completedAt:null,healthy:status.fixturesConnected===true};}
