'use client';
import {useEffect,useRef,useState} from 'react';
type GoogleIdentity={initialize:(options:{client_id:string;nonce:string;callback:(response:{credential:string})=>void})=>void;renderButton:(target:HTMLElement,options:{theme:string;size:string;type:string})=>void};
export default function Login(){const target=useRef<HTMLDivElement>(null);const [error,setError]=useState('');const [status,setStatus]=useState('Loading Google sign-in…');
 useEffect(()=>{let alive=true;async function start(){try{const r=await fetch('/api/auth/config',{cache:'no-store'});if(!r.ok)throw new Error('Sign-in is temporarily unavailable.');const config=await r.json() as {configured:boolean;clientId:string;nonce:string};if(!config.configured){if(alive)setStatus('Google sign-in has not been configured for this host yet.');return;}
 const identity=()=> (window as Window&{google?:{accounts:{id:GoogleIdentity}}}).google?.accounts.id;
 if(!identity())await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Google sign-in could not load. Please refresh.'));document.head.appendChild(script);});
 if(!alive||!target.current)return;const google=identity();if(!google)throw new Error('Google sign-in unavailable.');google.initialize({client_id:config.clientId,nonce:config.nonce,callback:async({credential})=>{setStatus('Signing in…');try{const response=await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential})});const data=await response.json() as {error:string};if(!response.ok)throw new Error(data.error);window.location.assign('/');}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.');setStatus('Refresh this page to try again.');}}});google.renderButton(target.current,{theme:'outline',size:'large',type:'standard'});setStatus('');}catch(e){if(alive)setError(e instanceof Error?e.message:'Sign-in failed.');}}void start();return()=>{alive=false;};},[]);
 return <main className="login-panel"><a className="brand" href="/">touchline.</a><h1>Your picks. Your portfolio.</h1><p>Sign in with Google to start with $1,000 virtual dollars and track your progress across devices.</p><div ref={target}/>{status&&<p role="status">{status}</p>}{error&&<p role="alert" className="negative">{error}</p>}<p className="source-note">After you trade, your player alias, portfolio value, and return appear on the leaderboard for 30 days. Your Google name and email are not displayed. All money is virtual.</p><a href="/">Back to match markets</a></main>;
}
