import ts from 'typescript';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../lib/market.ts',import.meta.url),'utf8');
const output=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {UNIT,examples,freshAccount,executeTrade,settle,pricesFromOdds,matchAllowance,portfolioValue,credit}=await import('data:text/javascript;base64,'+Buffer.from(output).toString('base64'));
const m=examples[0],a=freshAccount(),p=m.prices[2];
assert.equal(pricesFromOdds([1.8,3.8,4.5]).reduce((s,p)=>s+p,0),UNIT);
assert.ok(m.prices[2]<m.prices[0]);
const bought=executeTrade(a,m,'away','buy',100,p);
assert.equal(bought.cash,a.cash-100*p);assert.equal(a.positions.length,0);
const moved={...m,prices:[400000,300000,300000]};
const sold=executeTrade(bought,moved,'away','sell',40,300000);
assert.equal(sold.cash,bought.cash+12000000);assert.equal(sold.positions[0].shares,60);assert.equal(sold.positions[0].cost,60*p);
assert.throws(()=>executeTrade(a,m,'away','buy',100000,p),/Not enough/);
assert.throws(()=>executeTrade(bought,m,'away','sell',101,p),/do not own/);
assert.throws(()=>executeTrade(a,m,'away','buy',1.5,p),/whole number/);
assert.throws(()=>executeTrade(a,m,'away','buy',-5,p),/whole number/);
assert.throws(()=>executeTrade(a,m,'away','buy',5,p+1),/price changed/);
assert.throws(()=>executeTrade(a,{...m,kickoff:'2020-01-01T00:00:00Z'},'away','buy',5,p),/kickoff/);
assert.throws(()=>executeTrade(a,{...m,closed:true},'away','buy',5,p),/kickoff/);
const win=settle(bought,[{...m,result:'away'}]);assert.equal(win.cash,bought.cash+100*UNIT);assert.equal(win.positions.length,0);
assert.deepEqual(settle(win,[{...m,result:'away'}]),win);
const loss=settle(bought,[{...m,result:'home'}]);assert.equal(loss.cash,bought.cash);assert.equal(loss.positions.length,0);
assert.deepEqual(settle(bought,[m]),bought);
console.log('PASS: normalized prices, underdog weighting, buy/sell accounting, insufficient funds, overselling, invalid quantity, quote changes, kickoff lock, win/loss settlement, and duplicate settlement.');
assert.equal(credit(1000*UNIT),'$1,000.00');
const exact={...m,prices:[500000,250000,250000]};
assert.equal(matchAllowance(a,exact.id,[exact]).remaining,100*UNIT);
const boundary=executeTrade(a,exact,'home','buy',200,500000);
assert.equal(matchAllowance(boundary,exact.id,[exact]).remaining,0);
assert.throws(()=>executeTrade(boundary,exact,'away','buy',1,250000),/10% match limit/);
assert.throws(()=>executeTrade(a,exact,'home','buy',201,500000),/10% match limit/);
const mixed=executeTrade(executeTrade(a,exact,'home','buy',100,500000),exact,'draw','buy',200,250000);
assert.equal(matchAllowance(mixed,exact.id,[exact]).committed,100*UNIT);
assert.throws(()=>executeTrade(mixed,exact,'away','buy',1,250000),/10% match limit/);
const released=executeTrade(boundary,exact,'home','sell',20,500000);
assert.equal(matchAllowance(released,exact.id,[exact]).remaining,10*UNIT);
assert.equal(executeTrade(released,exact,'draw','buy',40,250000).cash,900*UNIT);
const second={...exact,id:'another-match'};
assert.doesNotThrow(()=>executeTrade(boundary,second,'home','buy',200,500000,Date.now(),[exact,second]));
const richer={...a,cash:1500*UNIT};assert.equal(matchAllowance(richer,exact.id,[exact]).limit,150*UNIT);
const markedGain={...exact,prices:[750000,125000,125000]};
assert.equal(portfolioValue(boundary,[markedGain]),1050*UNIT);
assert.equal(matchAllowance(boundary,exact.id,[markedGain]).remaining,5*UNIT);
const markedLoss={...exact,prices:[250000,375000,375000]};assert.equal(matchAllowance(boundary,exact.id,[markedLoss]).remaining,0);
assert.doesNotThrow(()=>executeTrade(boundary,markedLoss,'home','sell',1,250000));
assert.throws(()=>executeTrade(a,{...exact,quoted:false},'home','buy',1,500000),/not available/);
const fixtureSource=readFileSync(new URL('../lib/fixtures.ts',import.meta.url),'utf8');
const fixtureCode=ts.transpileModule(fixtureSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {mapFixtures,teamKey}=await import('data:text/javascript;base64,'+Buffer.from(fixtureCode).toString('base64'));
const bootstrap={teams:[{id:1,name:'Man City'},{id:2,name:'Spurs'}],events:[{id:6,name:'Gameweek 6',is_current:true,is_next:false},{id:7,name:'Gameweek 7',is_current:false,is_next:true}]};
const fixture={id:1,code:9876,event:6,team_h:1,team_a:2,kickoff_time:'2026-10-10T15:00:00Z',started:false,finished:false,finished_provisional:false,team_h_score:null,team_a_score:null};
const quote={...exact,id:'odds-id',home:'Manchester City',away:'Tottenham Hotspur',kickoff:fixture.kickoff_time};
const mapped=mapFixtures(bootstrap,[fixture],[],[quote]);assert.equal(mapped.markets[0].quoted,true);assert.equal(mapped.selectedWeek,6);
const withoutOdds=mapFixtures(bootstrap,[fixture],[],[]).markets[0];assert.equal(withoutOdds.quoted,false);assert.equal(withoutOdds.prices.length,0);assert.equal(withoutOdds.closed,true);
const provisional=mapFixtures(bootstrap,[{...fixture,started:true,finished:false,finished_provisional:true,team_h_score:2,team_a_score:1}],[],[]);assert.equal(provisional.markets[0].result,undefined);
const finished=mapFixtures(bootstrap,[{...fixture,finished:true,finished_provisional:true,team_h_score:2,team_a_score:1}],[],[]);assert.equal(finished.markets[0].result,'home');assert.equal(finished.selectedWeek,7);
const draw=mapFixtures(bootstrap,[{...fixture,finished:true,finished_provisional:true,team_h_score:1,team_a_score:1}],[],[]);assert.equal(draw.markets[0].result,'draw');
const missingScore=mapFixtures(bootstrap,[{...fixture,finished:true,finished_provisional:true,team_h_score:null,team_a_score:1}],[],[]);assert.equal(missingScore.markets[0].result,undefined);
const rescheduled=mapFixtures(bootstrap,[{...fixture,kickoff_time:'2026-10-12T15:00:00Z'}],mapped.markets,[quote]);assert.equal(rescheduled.markets[0].id,mapped.markets[0].id);assert.equal(rescheduled.markets[0].quoted,false);
assert.equal(teamKey("Nott'm Forest"),'nottingham forest');
console.log('PASS: USD formatting, exact 10% boundary, aggregate outcomes, sell/rebuy allowance, per-match separation, bankroll changes, fixture matching, missing odds, final-only results, draws, weekly rollover and rescheduling.');
