import {getPlayer,sameOrigin} from '@/lib/player-auth';
import {db,loadAccount,saveAccount,settleAccount,recordHistory,readHistory,settlementStatus} from '@/lib/store';
import {connected,fresh} from '@/lib/feed';
import {liveMarkets} from '@/lib/live-feed';
import {examples,executeTrade,freshAccount,outcomes,pricesFromOdds,settle,type Market,type Outcome,type Account} from '@/lib/market';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function state(req:Request){const user=await getPlayer();const mode=new URL(req.url).searchParams.get('mode')==='live'?'live':'demo';const id=user?`${user.userId}:${mode}`:null;let account=id?await loadAccount(id):freshAccount();const feed=mode==='live'?await liveMarkets():{markets:account.demoMarkets??structuredClone(examples),notice:'Illustrative fixtures and odds. Demo trades use a separate virtual balance.',fetchedAt:0,weeks:[],selectedWeek:0,fixturesUpdated:0,fixturesConnected:false};if(id&&mode==='live')account=(await settleAccount(id,feed.markets)).account;return {user,mode,id,account,...feed,connected:connected()};}
export async function GET(req:Request){try{const s=await state(req);if(s.id)await recordHistory(s.id,s.account,s.markets);const history=s.id?await readHistory(s.id):[];return json({history,playerName:s.user?.displayName??null,settlementStatus:await settlementStatus(),account:s.account,markets:s.markets,notice:s.notice,connected:s.connected,fetchedAt:s.fetchedAt,weeks:s.weeks,selectedWeek:s.selectedWeek,fixturesUpdated:s.fixturesUpdated,fixturesConnected:s.fixturesConnected,signedIn:!!s.user});}catch{return json({error:'Could not load your portfolio. Please refresh to try again.'},503);}}
export async function POST(req:Request){try{if(!sameOrigin(req))return json({error:'Cross-site requests are not allowed.'},403);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'JSON required.'},415);const s=await state(req);if(!s.id)return json({error:'Sign in to save your predictions.'},401);const body=await req.json() as Record<string,unknown>;if(body.revision!==s.account.revision)return json({error:'Your portfolio changed. Refresh and try again.'},409);let next:Account=s.account;
 if(body.action==='trade'){const m=s.markets.find(m=>m.id===body.marketId);if(!m)throw new Error('This market is not available.');if(s.mode==='live'&&!fresh(m))throw new Error('This quote is stale. Trading is paused until a fresh quote arrives.');next=executeTrade(s.account,m,body.outcome as Outcome,body.side as 'buy'|'sell',body.shares as number,body.price as number,Date.now(),s.markets);}
 else if(body.action==='settle'){next=settle(s.account,s.markets);}
 else if(body.action==='simulate'&&s.mode==='demo'){next=structuredClone(s.account);next.demoMarkets=s.markets.map(m=>{if(m.result)return m;const odds=m.odds.map(o=>Math.max(1.08,Math.round(o*(.9+Math.random()*.2)*100)/100));return {...m,odds,prices:pricesFromOdds(odds),updated:new Date().toISOString()};});}
 else if(body.action==='demo-result'&&s.mode==='demo'){if(!outcomes.includes(body.outcome as Outcome))throw new Error('Choose home, draw or away.');const m=s.markets.find(m=>m.id===body.marketId);if(!m||m.result)throw new Error('Choose an unsettled demo match.');next=structuredClone(s.account);next.demoMarkets=s.markets.map(m=>m.id===body.marketId?{...m,result:body.outcome as Outcome,closed:true}:m);next=settle(next,next.demoMarkets!);}
 else throw new Error('Unsupported action.');
 next=await saveAccount(s.id,next);if(body.action==='trade'&&s.mode==='live'){try{await db().prepare('UPDATE players SET last_trade_at=? WHERE id=?').bind(Date.now(),s.user!.userId).run();}catch{console.error('Trade saved; leaderboard activity update pending.');}}let history:Awaited<ReturnType<typeof readHistory>>=[];let health:Awaited<ReturnType<typeof settlementStatus>>={completedAt:null,healthy:false};try{await recordHistory(s.id,next,s.mode==='demo'?next.demoMarkets??s.markets:s.markets);history=await readHistory(s.id);health=await settlementStatus();}catch{console.error("Portfolio saved; history capture unavailable.");}return json({history,playerName:s.user?.displayName??null,settlementStatus:health,account:next,markets:next.demoMarkets&&s.mode==='demo'?next.demoMarkets:s.markets,notice:s.notice,connected:s.connected,fetchedAt:s.fetchedAt,weeks:s.weeks,selectedWeek:s.selectedWeek,fixturesUpdated:s.fixturesUpdated,fixturesConnected:s.fixturesConnected,signedIn:true});
 }catch(e){const msg=e instanceof Error?e.message:'Could not save your action.';return json({error:msg.includes('D1')||msg.includes('SQL')?'Storage unavailable. Your action was not saved.':msg},400);}}
